### ISSUE TITLE
Where should I place the Components folder?

### ISSUE THREAD

**Issue by chenzheio** [juhwannn/next-express-boilerplate#1]
Where should I place the Components folder?

**Comment by juhwannn** [comment]
> Components 폴더는 어디에 두어야 합니까?

It is recommended to create and use a directory named components under the root directory. 

thank you for using :)

**Comment by chenzheio** [comment]
Do you plan to make a template that supports typescript?

**Comment by juhwannn** [comment]
> Typescript를 지원하는 템플릿을 만들 계획이 있나요?

Of course there is. But I don't think it will be soon
